import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import ClientOnly from './components/ClientOnly'
import Navbar from './components/Navbar/Navbar'
import ToasterProvider from './providers/ToasterProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <ClientOnly>
          <ToasterProvider/>
          <Navbar/>
          <hr className='bg-white'/>
        </ClientOnly>
        <div className='pb-20 pt-28'>
          {children}
        </div>
      </body>
    </html>
  )
}
